import type { Metadata } from "next";
import ClientProvider from "@/components/ClientProvider";
import { IBM_Plex_Sans_KR, Orbit } from "next/font/google";
// import localFont from "next/font/local";
import "@/styles/globals.css";
import "@/styles/common.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const imb_plex_sans_kR = IBM_Plex_Sans_KR({
  weight: ["400", "500", "600", "700"],
  variable: "--font-IBM_Plex_Sans_KR",
  subsets: ["latin"],
  display: "swap",
});

const orbit_regular = Orbit({
  weight: ["400"],
  variable: "--font-orbit_regular",
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${imb_plex_sans_kR.variable} ${orbit_regular.variable}`}>
      <body>
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}
